---

inherits:
  - "strictness_veryhigh"

strictness: "veryhigh"
test-warnings: true
doc-warnings: true
member-warnings: true

ignore-paths:
  - "venv"
  - "venv.bak"
  - ".venv"
  - ".venv.bak"
  - "docs"
  # - "test"

pylint:
  disable:
    - "bad-continuation"  # there is a conflict with black in function arguments
    - "empty-docstring"
    - "fixme"
    - "line-too-long"
    - "missing-docstring"
    - "missing-module-docstring"
    - "no-else-raise"
    - "no-else-return"
    - "too-few-public-methods"
    - "too-many-arguments"
    - "wrong-import-order"
  options:
    max-line-length: 108
    extension-pkg-whitelist:
      - "pydantic"
    max-args: 7
    good-names:
      # counters
      - "i"
      - "j"
      - "k"
      - "n"
      # dimensions
      - "h"
      - "w"
      - "l"
      # vectors
      - "x"
      - "y"
      - "z"
      # files
      - "fd"
      # pandas
      - "df"
      - "sr"
      - "ts"
      # geopandas
      - "gs"
      - "gf"
      # xarray
      - "ds"
      - "da"
      # matplotlib
      - "ax"
      - "rc"
      # various
      - "logger"
      - "router"
      - "app"
      - "env"
      # alembic
      - "revision"
      - "down_revision"
      - "branch_labels"
      - "depends_on"
    contextmanager-decorators:
      - "contextlib.contextmanager"
      - "decorator.contextmanager"

mccabe:
  run: true

pycodestyle:
  options:
    max-line-length: 108
  disable:
    - "E203"  # disable whitespace before colon - useful for numpy slicing
    - "E501"  # disable line too length. No reason to check for line length in each and every tool

pydocstyle:
  run: false
  disable:
    - 'D400'
    - 'D401'
